// Generated by CoffeeScript 1.12.7
(function() {
  this.L || (this.L = {});

  L.Home = (function() {
    function Home() {
      this.setup_lang_picker();
      $(document.body).on("click", ".top_link", (function(_this) {
        return function(e) {
          $(window).scrollTop(0);
          return false;
        };
      })(this));
      this.update_lang();
      this.setup_search();
    }

    Home.prototype.setup_search = function() {
      var drop;
      drop = $("#search_drop");
      if (drop.length) {
        return L.setup_search(drop, {
          index: drop.data("index"),
          root: drop.data("root")
        });
      }
    };

    Home.prototype.update_lang = function() {
      var lang, m;
      if (m = window.location.hash.match(/\blang=(\w+)\b/)) {
        lang = m[1];
        return $(document.body).toggleClass("show_lua", lang === "lua");
      }
    };

    Home.prototype.setup_lang_picker = function() {
      return $(document.body).on("click", ".lang_toggle", (function(_this) {
        return function(e) {
          window.location.hash = $(e.currentTarget).data("hash");
          return setTimeout(function() {
            return _this.update_lang();
          }, 1);
        };
      })(this));
    };

    return Home;

  })();

}).call(this);
